### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by liborw** [ros-melodic-arch/ros-melodic-rosbag-storage#1]
Arch python version is now 3.8, so all ros packages that depends on python wont build.

**Comment by jwhendy** [comment]
This [isn't one of them](https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/8). Did you have a build error, and if so, could you post it?

**Comment by liborw** [comment]
Sorry, probably same problem, I have solved it by changing the version to 3.8 in all PKGBUILDs.

**Comment by acxz** [comment]
Only certain packages (see: https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/8) require python3.8 to be explicitly stated. Changing the python version for all PKGBUILDs is the incorrect solution, rebuilding all of your python dependent packages in the AUR is the way to go about it.
Coincidentally, you probably rebuilt all your packages in that process so it worked out in the end.

Going ahead and closing this issue.
